### ISSUE TITLE
metadataとかをいい感じにする

### ISSUE THREAD

**Issue by addtobasic** [diawel/spoon#11]
## 概要

デフォルトのfaviconだったりタイトルだったりすると悲しいので変える.

## 期限

faviconぽいのが上がり次第

## やること

- titleの編集
- faviconの編集
- OGP画像作成
- OGP画像設定

## 参考

https://nextjs-ja-translation-docs.vercel.app/docs/api-reference/next/head
https://nextjs.org/docs/app/api-reference/file-conventions/metadata/manifest

**Comment by diawel** [comment]
ついでに`manifest.json`もお願いします

**Comment by diawel** [comment]
残りタスク
- スプラッシュスクリーン

**Comment by diawel** [comment]
参考情報 #29 にあります

**Comment by yu-onsen** [comment]
各端末サイズに合わせたスプラッシュスクリーン画像を作成した
