### ISSUE TITLE
セルへのsvgの色変え, 貼り付け

### ISSUE THREAD

**Issue by addtobasic** [diawel/spoon#18]
## 概要

一覧表示されているアイスにそれぞれの色を変えたsvg画像を表示する.
一例としてセルは下の画像のようになる.
![image](https://github.com/diawel/spoon/assets/40308976/174e3372-cb23-4b12-a717-44cd0d9d8545)

## 期限

データ受け渡しが終わり次第

## やること

- データの取得.
- patternに応じた各セルへの割当て.
- アイスが無いときは下の画像を表示するようにする.
![image](https://github.com/diawel/spoon/assets/40308976/20654367-4617-4118-a43b-0a31795d57df)

**Comment by diawel** [comment]
#3 と一緒にもらいます！
