### ISSUE TITLE
アイス画像の生成機能の実装する

### ISSUE THREAD

**Issue by addtobasic** [diawel/spoon#2]
## 概要
#1 で撮った写真からアイス画像を生成する.

## やること
- 出来上がったデザインの実装.
- #1 で抽出した色からアイス画像の生成.
- ダウンロードボタンから画像のダウンロード.

**Comment by diawel** [comment]
一旦コンセプト的には無しでも良いと判断したためクローズ
もしやることになれば再度オープン
