### ISSUE TITLE
過去のアイス一覧ページ

### ISSUE THREAD

**Issue by addtobasic** [diawel/spoon#3]
## 概要
#2 で生成したアイスの写真からアイスの一覧ページを作成する.

## やること
- Figmaでデザイン ゆめか -12/12夜
- 出来上がったデザインの実装 げんし -12/14にはできてる

**Comment by diawel** [comment]
タスク残り
- DB繋ぎ込み

**Comment by diawel** [comment]
続き実装担当します。

**Comment by yu-onsen** [comment]
アイスの影が真下になっているので右に出るように修正してほしい
写真との同化を防ぐために一覧ページのアイスをシール風にしても良いかも（要相談）
@Ririri0803
