### ISSUE TITLE
履歴ページへの遷移時にアニメーションをさせる

### ISSUE THREAD

**Issue by addtobasic** [diawel/spoon#37]
## 概要

履歴ページに移動したときになにも起こらずに寂しいのでアニメーションを追加する. ついでに画像の切替時にも欲しいかも.

## 期限

12/17

## やること

- アニメーションの実装
- アニメーション適用

## メモ
- https://qiita.com/KokiSakano/items/e3a42a12f5de3c9f88ea
- https://qiita.com/arrow2nd/items/b16385cf22c567fbbf33
- https://zenn.dev/code_diver/articles/fc02dec8960cb7

**Comment by diawel** [comment]
全体会議で不要と判断したためクローズ。
類似の変更は #40 で行います。

**Comment by diawel** [comment]
全体会議で不要と判断したためクローズ。
類似の変更は #40 で行います。
