### ISSUE TITLE
UX改善

### ISSUE THREAD

**Issue by diawel** [diawel/spoon#40]
## 概要

アプリケーション全体のUXを調整する。

## 期限

12/17

## やること

- ページ遷移アニメーション
- ユーザーによる選択禁止
- りれきページで選択中のセルがわかるようにする
他にも気づいたとこあったら教えて

**Comment by addtobasic** [comment]
現在選択されているセルに対して選択されていると分かるものが必要かなって思った

**Comment by diawel** [comment]
🦀
追記します

**Comment by addtobasic** [comment]
いったんcloseするけど, なにか他にもUXの改善点があればreopenするなり新しくissue立てるなりしましょう
