### ISSUE TITLE
アイス画像の作成

### ISSUE THREAD

**Issue by addtobasic** [diawel/spoon#7]
## 概要
アプリ上で使用するアイスの画像をsvgで作成する。
## 期限
12/13
## やること
figmaかイラレで画像を作成

**Comment by diawel** [comment]
丸アイス完成！
![スクリーンショット 2023-12-13 23 37 42](https://github.com/diawel/spoon/assets/38136957/fc0d4981-ab21-493e-8a5b-e61d23799367)

**Comment by diawel** [comment]
残りタスク
- 隙間問題どうにかするかもしれない
