### ISSUE TITLE
Vercelにデプロイする

### ISSUE THREAD

**Issue by addtobasic** [diawel/spoon#9]
## 概要

Next.jsアプリをVercelにデプロイする.

## 期限

未定. #8 が終わり次第.

## やること

- Next.jsアプリをVercelにデプロイする.
- アカウント関係で面倒なことにならないことを祈る.

**Comment by diawel** [comment]
引き継ぎました

**Comment by diawel** [comment]
状況の整理
- 現状production branchはmainのみにしてる
- mainへのコミットは問答無用で https://spoon-p2hacks.vercel.app/ に公開される
- Diawelがdevelopで`vercel --prod`すると、developの内容でビルドされ https://spoon-p2hacks.vercel.app/ に公開される
- developへのコミットを別のドメインにデプロイすることはできるけどそれはチームのメンバーじゃないと見れない（チームは有料版の機能）
- さっき https://spoon-p2hacks.vercel.app/ の内容が公開されてなかったのは設定が間違っていたため （https://spoon-p2hacks.vercel.app/ をproduction branchではないdevelopに割り当てていたため、公開されなくなっていた）

**Comment by diawel** [comment]
12/11の定例でproduction branchをdevelopにすることにした
